name: Backend CI
run-name: Running Backend tests.
on: [push]
jobs:
  Backend-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cb Backend
      - run: npm i
      - run: npm run test
